services:
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: crm-api-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./application:/var/www
    enviroment:
      - COMPOSER_HOME=/composer
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=local
    networks:
      - crm-api-network
  
  nginx:
    container_name: crm-api-ngix
    image: nginx:1.27.4-alpine-slim
    restart: always
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./application:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - crm-api-network

networks:
  crm-api-network:
    driver: bridge