services:
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: crm-api-app
    restart: always
    working_dir: /var/www/application
    volumes:
      - ./:/var/www
      - ./application:/var/www/application
    environment:
      - COMPOSER_HOME=/composer
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=local
      - APP_KEY=base64:VkAkJhAPsfbYrtuv2ye+p7ZWy5h1qXv6qNpeTwej1W8=
    networks:
      - crm-api-network
    depends_on:
      - nginx
  
  nginx:
    container_name: crm-api-nginx
    image: nginx:1.27.4-alpine-slim
    restart: always
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./application:/var/www/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx/
    networks:
      - crm-api-network

networks:
  crm-api-network:
    driver: bridge